DROP TABLE IF EXISTS "comments";
DROP TABLE IF EXISTS "users" CASCADE;
DROP TABLE IF EXISTS "items" CASCADE;
DROP TABLE IF EXISTS "requests";
DROP TABLE IF EXISTS "bookings"; --Оставлено, чтобы пройти тесты. Закомментировать для работы--

CREATE TABLE IF NOT EXISTS users
(
    user_id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(64)                             NOT NULL,
    email VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (user_id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS items
(
    item_id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(255)                            NOT NULL,
    description  VARCHAR(255)                            NOT NULL,
    available BOOLEAN                                 NOT NULL,
    owner_id     BIGINT                                  NOT NULL,
    request   BIGINT,
    CONSTRAINT pk_item PRIMARY KEY (item_id),
    CONSTRAINT fk_owner FOREIGN KEY (owner_id) REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE TABLE requests
(
    id           bigint  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    description  varchar NOT NULL,
    requestor_id bigint  NOT NULL,
    CONSTRAINT pk_request PRIMARY KEY (id),
    CONSTRAINT fk_requestor FOREIGN KEY (requestor_id) REFERENCES users (user_id) ON DELETE CASCADE,
    CONSTRAINT fk_item FOREIGN KEY (requestor_id) REFERENCES items (item_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS comments
(
    comments_id        bigint    NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    text   varchar   NOT NULL,
    item_id   BIGINT    NOT NULL,
    author_id bigint    NOT NULL,
    created   timestamp NOT NULL,
    CONSTRAINT pk_comments PRIMARY KEY (comments_id),
    CONSTRAINT fk_comments_item FOREIGN KEY (item_id) REFERENCES items (item_id) ON DELETE CASCADE,
    CONSTRAINT fk_author FOREIGN KEY (author_id) REFERENCES users (user_id) ON DELETE CASCADE
);

CREATE TABLE bookings
(
    booking_id         bigint    NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    start_time timestamp NOT NULL,
    end_time   timestamp NOT NULL,
    item_id    bigint    NOT NULL,
    booker_id  bigint    NOT NULL,
    status     varchar   NOT NULL,
    CONSTRAINT pk_bookings PRIMARY KEY (booking_id),
    CONSTRAINT fk_bookings_item FOREIGN KEY (item_id) REFERENCES items (item_id) ON DELETE CASCADE,
    CONSTRAINT pk_booker FOREIGN KEY (booker_id) REFERENCES users (user_id) ON DELETE CASCADE
)